/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DropdownWc {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface GraphWc {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDropdownWcElement extends Components.DropdownWc, HTMLStencilElement {
    }
    var HTMLDropdownWcElement: {
        prototype: HTMLDropdownWcElement;
        new (): HTMLDropdownWcElement;
    };
    interface HTMLGraphWcElement extends Components.GraphWc, HTMLStencilElement {
    }
    var HTMLGraphWcElement: {
        prototype: HTMLGraphWcElement;
        new (): HTMLGraphWcElement;
    };
    interface HTMLElementTagNameMap {
        "dropdown-wc": HTMLDropdownWcElement;
        "graph-wc": HTMLGraphWcElement;
    }
}
declare namespace LocalJSX {
    interface DropdownWc {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface GraphWc {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "dropdown-wc": DropdownWc;
        "graph-wc": GraphWc;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dropdown-wc": LocalJSX.DropdownWc & JSXBase.HTMLAttributes<HTMLDropdownWcElement>;
            "graph-wc": LocalJSX.GraphWc & JSXBase.HTMLAttributes<HTMLGraphWcElement>;
        }
    }
}
